# Generated by Django 5.2 on 2025-04-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('adhoc', 'Ad-hoc'), ('paused', 'Paused')], default='Ad-hoc', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='next_session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='paypal_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.CharField(choices=[('UK', 'UK'), ('Europe', 'Europe'), ('USE', 'US East'), ('USW', 'US West'), ('USC', 'US Central'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Asia', 'Asia'), ('Other', 'Other')], default='UK', max_length=50),
        ),
    ]
