# Generated by Django 5.2 on 2025-04-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('free', 'Free'), ('lightning', 'Lightning'), ('package', 'Package')], max_length=50)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clients.client')),
            ],
        ),
    ]
