# Generated by Django 5.2 on 2025-04-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_no_show',
            field=models.BooleanField(default=False),
        ),
    ]
