# Generated by Django 5.2 on 2025-04-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_session_is_no_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='next_session_date',
        ),
    ]
