# Generated by Django 5.2 on 2025-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_next_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('Enquiring', 'Enquiring'), ('Vibe-Check Booked', 'Vibe-Check Booked'), ('Post-Vibe', 'Post-Vibe'), ('Paying', 'Paying')], default='enquiring', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.CharField(choices=[('UK', 'UK'), ('Europe', 'Europe'), ('US East', 'US East'), ('US West', 'US West'), ('US Central', 'US Central'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Asia', 'Asia'), ('Other', 'Other')], default='UK', max_length=50),
        ),
    ]
