# Generated by Django 5.2 on 2025-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_client_status_alter_client_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Three-session package', 'Three-session package'), ('Six-session package', 'Six-session package')], default='free', max_length=50),
        ),
    ]
