# Generated by Django 5.2 on 2025-04-14 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'csv'])]),
        ),
    ]
