# Generated by Django 5.2 on 2025-04-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clientdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
