# Generated by Django 5.2 on 2025-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paid_sessions_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
