# Generated by Django 5.2 on 2025-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_paid_sessions_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='paypal_link',
        ),
        migrations.AddField(
            model_name='client',
            name='payment_info',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_tier',
            field=models.CharField(choices=[('Free', 'Free'), ('3-session package', '3-session package'), ('6-session package', '6-session package')], default='Free', max_length=50),
        ),
    ]
