# Generated by Django 5.2 on 2025-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_client_paypal_link_client_payment_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
