# Generated by Django 5.2 on 2025-04-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_rename_phone_number_client_social_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='payment_tier',
            new_name='current_package',
        ),
    ]
