# Generated by Django 5.2 on 2025-04-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_rename_payment_tier_client_current_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='completed_sessions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_status',
            field=models.CharField(choices=[('No need', 'No need'), ('Generated', 'Generated'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Issue', 'Issue')], default='No need', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='no_show_sessions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
