# Generated by Django 5.2 on 2025-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_notification_notification_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_lifecycle',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=50),
        ),
    ]
