# Generated by Django 5.2 on 2025-04-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_client_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_lifecycle',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
    ]
