# Generated by Django 5.2 on 2025-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_client_client_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lifecycle_status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
