# Generated by Django 5.2 on 2025-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.DecimalField(decimal_places=0, default=80, max_digits=5),
        ),
    ]
