# Generated by Django 5.2 on 2025-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_alter_client_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_revenue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
